version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@4.1.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python test_circle_ci/manage.py test
          name: Test
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  main:
    jobs:
      - build-and-test
        context: slack-secrets
